const MODULOS = {
  REPORTES: 1,
  PROVEEDORES: 2,
  PRODUCTOS: 3,
  CLIENTES: 4,
  CREDITOS: 5,
  VENTAS: 6,
  COMPRAS: 7,
  GASTOS: 8,
  HISTORIAL: 9,
  FACTURAS_DE_PROVEEDORES: 10,
  FACTURAR: 11,
  CONFIGURACIONES: 12,
};

const MEDIOS_DE_PAGO = {
  CAJAS: 1,
  TRANSFERENCIA_BANCARIA: 2,
  SINPE_MOVIL: 3,
  TARJETA_DE_DEBITO_O_CREDITO: 4,
};

const TAMANIO_PAGINA_POR_DEFECTO = 10;

const INVOICE_TYPE = {
  CREDITO: 5,
  CONTADO: 6,
  TARJETA: 7,
  PROFORMA: 8,
};

export { MODULOS, TAMANIO_PAGINA_POR_DEFECTO, MEDIOS_DE_PAGO, INVOICE_TYPE };